### ISSUE TITLE
Detect Dropbox Link

### ISSUE THREAD

**Issue by jbudd83** [fwenzel/upshot#71]
Dropbox version 3.0.3
OSX Version 10.10.1

I am having an issue where Upshot is not detecting the link from Drop Box. 

Not sure if this has anything to do with it but the screen shot you have on that step: http://screencast.com/t/SWIMUhWdv  is different from what the dropbox menu looks like on my computer: http://screencast.com/t/nlL6jBMuBs

P.S. sorry for the screencast links. I am trying to get upshot installed to replace it :)

**Comment by jbudd83** [comment]
here is a link that dropbox is generating. https://www.dropbox.com/s/7zxcgzfao1am5fx/Untitled-1.png?dl=0

**Comment by fwenzel** [comment]
You're not using the Dropbox "Public" folder. In the Preferences window there is a (?) button next to the detect button, which leads here: https://www.dropbox.com/help/16

Please use the instructions there for Dropbox to give you a Public folder, then generate a URL (Right click, "Copy Public Link") in that folder, which will look something like this: https://dl.dropboxusercontent.com/u/18779383/How%20to%20use%20the%20Public%20folder.rtf

**Comment by fwenzel** [comment]
(The difference between the Public folder and regular Dropbox sharing is that the Public folder lets you link directly to a file, as if it was a straight up web server; instead of an interstitial Dropbox website that has the shared file *on it*)

**Comment by jbudd83** [comment]
Thank you for your help! It looks like I have to upgrade to Pro or Business account for this to work.

**Comment by fwenzel** [comment]
"It looks like I have to upgrade to Pro or Business account for this to work."

Oh? That would be complete news to me. I do not have a paid account, nor does anyone I know.

**Comment by fwenzel** [comment]
(Unrelated, I'll have you know I am working on Issue #70 but it's not trivial, so not quite done yet. But when it *is* done, you'll be able to upload to different places, not just Dropbox).

**Comment by fwenzel** [comment]
Dropbox writes:

> Creating a Public folder
>
> Dropbox links give you everything you need to share and preview files and folders. However, if you’re just a diehard fan of Public folders, click here to enable one on your account. Currently only Pro and Dropbox for Business users can enable Public folders, so you may have to upgrade first.

and the link points here: https://www.dropbox.com/enable_public_folder

Try that out?

**Comment by fwenzel** [comment]
That means, upload functionality outside of Dropbox has just become a lot more important.

**Comment by fwenzel** [comment]
I just tweeted that out to my followers. Sorry that I can't help you right now, and many thanks for pointing it out! I'll quickly get back to implementing better upload targets!

First will be imgur because it has a fairly easy API. After I get that straight, architecturally, I should be able to add many more over time (like SFTP, S3, and so on).

**Comment by jbudd83** [comment]
thank you for your follow up! I look forward to seeing more upload targets. +1 for S3

p.s. you should get a donation link ;) unless i am missing it...

**Comment by fwenzel** [comment]
Oh thank you for the suggestion, I shall put one on upshot.it, it would certainly be encouraging if someone bought me a coffee for this ;)

If you have bitcoin, I have a tipping button on my blog ;) http://fredericiana.com/2014/11/27/bitcoin-tipping/
